global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'producer'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'consumer'
    static_configs:
      - targets: ['host.docker.internal:8082']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'ai-service'
    static_configs:
      - targets: ['host.docker.internal:5178']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093'] 